# Generated by Django 4.2.20 on 2025-04-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
