# Generated by Django 4.2.20 on 2025-04-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_options_todo_created_at_todo_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
